server:
  port: 8081

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

certview:
  token:
    issuer: "https://auth.certview.local"
    audience: "certview-api"
